
import { Header } from "@/components/Header";
import "../styles/global.scss";
export const metadata = {
  title: 'Home | Ig News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    
    <html lang="en">
      
      
      
      <body>{children}</body>
    </html>
    </>
  )
}
